recipes:
    global:
        - applications::create_var_chef_cache
        - dotfiles::bash_it
        - dotfiles::inputrc
        - applications::bash
        - dotfiles::gitconfig
        - applications::ssh_config
        - dotfiles::vim
        - dotfiles::workspace
        - applications::mysql
        - applications::php56
        - dotfiles::sshconfig
    mac_os_x:
        # Modify some OSX default preferences
        - osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
        - osxdefaults::add_note_to_loginscreen
        - osxdefaults::automatically_illuminate_built-in_macbook_keyboard_in_low_light
        - osxdefaults::automatically_quit_printer_app_once_the_print_jobs_complete
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
        - osxdefaults::disable_auto-correct
        - osxdefaults::disable_front_row
        - osxdefaults::disable_resume_system-wide
        - osxdefaults::do_not_group_windows_by_application_in_mission_control
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_position_the_dock_on_the_left_side
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::enable_subpixel_font_rendering_on_non-apple_lcds
        - osxdefaults::expand_print_panel_by_default
        - osxdefaults::expand_save_panel_by_default
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_disable_the_warning_before_emptying_the_trash
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_show_path_bar
        - osxdefaults::finder_show_status_bar
        - osxdefaults::finder_small_sidebar_icon_size
        - osxdefaults::finder_unhide_home
        - osxdefaults::finder_use_column_view_in_all_finder_windows_by_default
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::save_screenshots_in_png_format
        - osxdefaults::save_screenshots_to_the_desktop
        - osxdefaults::set_computer_name
        - osxdefaults::set_terminal_profile
        - osxdefaults::speed_up_mission_control_animations
        - osxdefaults::tap_to_click
        - osxdefaults::turn_off_keyboard_illumination_when_computer_is_not_used_for_5_minutes
        # Install some software
        - applications::dnsmasq
        - applications::gnu-tar
        - applications::launchrocket
        - applications::omnigraffle
        - applications::sublime_text_3
        - applications::svgo
        # Modify the default sudo settings
        - sudoalt::default
        # Install node.js
        - nodejs::default
        # Install homebrew and homebrew cask, and install all apps mentioned
        # in the homebrewalt::apps and homebrewalt::cask_apps attributes
        - homebrewalt::default
attributes:
    mysql_root_password: "root"
    dotfiles:
        vimusers:
            - root
            - cbracco
        vim:
            bundle:
                - sleuth: git://github.com/tpope/vim-sleuth.git
                - sensible: git://github.com/tpope/vim-sensible.git
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - airline: https://github.com/bling/vim-airline
                - syntastic: git://github.com/scrooloose/syntastic.git
                - nerdtree: https://github.com/scrooloose/nerdtree.git
                - vim-css-color: https://github.com/ap/vim-css-color
    ssh:
        host_aliases:
            - ["berg", "24.97.51.246", 6969]
            - ["brs1", "54.225.128.165", 1212]
            - ["brs2", "54.235.149.173", 22]
            - ["brs321", "legacy.bigroomstudios.com", 1212]
            - ["brs421", "el421.bigroomstudios.com", 1212]
    git:
        name: Chris Bracco
        email: chris@cbracco.me
    osxdefaults:
        computername: Chris-Bracco-2014-MacBook-Pro
        loginmessage: If found please return this machine to Chris Bracco - (201) 953-3928 - chris@cbracco.me
        finder:
            preferred_view_style: clmv
    authorization:
        sudo:
            users:
                - cbracco
            passwordless: true
            include_sudoers_d: true
    homebrewalt:
        apps:
            - bash-completion
            - coreutils
            - git
            - git-extras
            - git-flow
            - htop-osx
            - imagemagick
            - libyaml
            - nmap
            - openssl
            - nginx
            - postgresql
            - pv
            - pwgen
            - python
            #- rsync
            - siege
            - watch
            - wget
            - xmlstarlet
        cask_apps:
            - adium
            - alfred
            - appcleaner
            - bartender
            - charles
            - colors
            - dropbox
            - evernote
            - firefox
            - google-chrome
            - google-hangouts
            - imagealpha
            - imageoptim
            - istat-menus
            - java
            - licecap
            - moom
            - onepassword
            - opera-mobile-emulator
            - rdio
            - send-to-kindle
            - sequel-pro
            - silverlight
            - sketch
            - skype
            - slack
            - stay
            - sonos
            - sourcetree
            - transmit
            - utorrent
            - virtualbox
            - vlc
    nodejs:
        apps:
            - bower
            - grunt
            - grunt-cli
            - gulp
            - less
            - uglify-js
            - uglifycss
    gems:
        - sass
    php-apps:
        - composer
